### ISSUE TITLE
network-cellular-4g and network-cellular-lte are identical

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-themes#5]
Consider detangling the network-cellular-4g and network-cellular-lte icons:

- 4g is a symbolic link to lte
- lte shows a 4G symbol

It would be nice if we had a real LTE symbol, for any device that is capable of doing LTE. Further down the road it needs to be checked if network-manager/ofono can report this correctly at all or not. Still, the icon would make sense to have.

**Comment by mariogrip** [comment]
then do we need to confuse the user with this? LTE is just "old 4g" but its still 4g. some of our devices supports LTE.

What we should make is an 4g+ symbol (aka LTE-A). maybe that's what you meant?

**Comment by Flohack74** [comment]
Well technically speaking LTE has lesser bandwidth than 4G, and its to me also not on the same technical level. So calling it "old 4G" is optimistic. To me ist just the question, can you see LTE icon when you are switched to 3G-only? Because this is what I would understand fom the technical documents. I dont know how this is implemented in ofono/rild in the end, how the limit/select the technology. But to me 4G is UMTS/HSDPA. Not less ;)
