### ISSUE TITLE
Create 4g+ symbol

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubuntu-themes#9]
we would also need an 4g+ icon

**Comment by cibersheep** [comment]
Ouh... that might be easy :D

**Comment by Flohack74** [comment]
I am still against:
_LTE is commonly marketed as "4G LTE and Advance 4G",[citation needed] but it does not meet the technical criteria of a 4G wireless service, as specified in the 3GPP Release 8 and 9 document series for LTE Advanced. LTE is also commonly known as 3.95G. The requirements were originally set forth by the ITU-R organization in the IMT Advanced specification. However, due to marketing pressures and the significant advancements that WiMAX, Evolved High Speed Packet Access and LTE bring to the original 3G technologies, ITU later decided that LTE together with the aforementioned technologies can be called 4G technologies.[3] The LTE Advanced standard formally satisfies the ITU-R requirements to be considered IMT-Advanced.[4] To differentiate LTE Advanced and WiMAX-Advanced from current 4G technologies, ITU has defined them as "True 4G".[5][6]_
Marketing pressure. Technically LTE is not 4G so lets educate our users ;) - And we will not have a Tru4G icon, which could be the closest we can get ;)

**Comment by mariogrip** [comment]
tbh i really think we should make it simple, its not that different is it?

and ofono puts them under the same enum, so its better to show 4G then L

**Comment by cibersheep** [comment]
So... with 4G and L icons are we set?

**Comment by mariogrip** [comment]
No, I think we should just have 4g and 4g+ :) my point being people don't really care about the difference between LTE and 4g since they pretty much deliver close to equal speed. but 4g+ (LTE-A) deliver a major speed boost. I dont really see a reason to make a difference between LTE and 4g? currently our whole ofono stack is built to not care for the difference it will be some work to enable it. right now it will just an L since thats whats defined by:  https://github.com/ubports/indicator-network/blob/95e75433bc3be33ddc7155873a77ba9bcc8bb7bb/src/indicator/icons.cpp#L56

but @Flohack74 wants LTE, 4g, LTE-A and 4g+ i think.

**Comment by mariogrip** [comment]
https://www.digitaltrends.com/mobile/4g-vs-lte/

> So the real question is, can you feel a difference between 4G and LTE networks? Is the speed of loading a page or downloading an app on your handheld device a lot faster if you have LTE technology built in? Probably not, unless you live in a city. While the difference between slower 3G networks and new 4G or LTE networks is certainly very noticeable, many of the 4G and “true 4G” networks have upload and download speeds that are almost identical. The rollout of LTE-A is starting to make a difference, but your mileage may vary. For now, LTE-A is the fastest connection available for wireless networks.

My point being why confuse users with and L and a 4g icon when it really does not matter to the user?

**Comment by mariogrip** [comment]
maybe @UniversalSuperBox can give some vise words?

**Comment by Flohack74** [comment]
Lets look at the outputs that ofonod has currently, I will not start rewriting the whole stuff just for that. If there is a quick win in adding more details then yes. What I wanted to say in the beginning: Do not symlink artwork, and lets design the icons as they are named. People get confused when the select 4g and lte icon and then see its the same. It looks like a bug if you dont know the symlink.
So we fixed that now, we can create more symbols, and then see how we can use them. Ok? =)

**Comment by UniversalSuperBox** [comment]
Symlinks seem to be created in icon packs to deal with different technologies having different names for the same concept (For example, the wi-fi strength icons all have a `nm-` variant symlink). There is no way we'll get rid of *all* of the symlinks in the icon packs, to do so would be to create duplicates of some icons (in concept or exact file structure).

For some cases, it's also possible that symlinks were created to allow vendors to override icons... why vendors couldn't just provide their own icons for the original names, I don't know. It's just a hypothesis.

In the case of the 4G and LTE icons, I'm guessing that "4G" for "LTE" was "good enough," but the developers wanted to return the *true* name in the appropriate condition (from ofono or the indicator, I'm not sure). 

Add to this all of the discussion above (LTE being branded 3.95G, [AT&T """mislabeling""" its LTE service as 5G](https://www.engadget.com/2019/01/07/att-faux-5g-icon-rolls-out/)), and it all becomes a mess.

So, if someone wants to make an icon or two, go for it. I'll merge it. If not, oh well. They won't be used until changes are made in ofono and the network indicator. If you'd like to discuss the recent addition of the L icon, please make a separate issue.

**Comment by cibersheep** [comment]
In the next days I can do a 4g+ icon. Then, it can be used if needed.
now L and 4g are 2 different icons (no symlinks).

PS: «now» means in the last merges PR :)

**Comment by denyskon** [comment]
[icons_4g+.zip](https://github.com/ubports/ubuntu-themes/files/3322212/icons_4g%2B.zip)
4g+ icon

**Comment by cibersheep** [comment]
Thank you @lxdb 
We would like the system icons to follow the Suru style. For example: https://github.com/ubports/ubuntu-themes/blob/xenial/suru-icons/status/scalable/network-cellular-5g.svg

More [info](https://gitlab.com/ubports/teams/ux-des/ubuntu-touch-human-interface-guidelines---hib/wikis/General%20Concepts/05-In-app%20Icons%20Design)

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab. Given this issue's needed-ness is still undecided, I'll close it instead of moving it. You may file it again at https://gitlab.com/ubports/core/suru-icon-theme if it is still relevant.
